/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cderose' at '1/4/18 10:12 PM' with Gradle 2.9
 *
 * @author cderose, @date 1/4/18 10:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
